# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: wire.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nwire.proto\x12\rbidirectional\"N\n\x04Text\x12\x13\n\x0bmessageType\x18\x01 \x01(\t\x12\x0e\n\x06sender\x18\x02 \x01(\t\x12\x10\n\x08receiver\x18\x03 \x01(\t\x12\x0f\n\x07message\x18\x04 \x01(\t\"\x15\n\x03Res\x12\x0e\n\x06status\x18\x01 \x01(\t\"\x07\n\x05\x45mpty2\x8a\x01\n\rBidirectional\x12:\n\rServer2Client\x12\x13.bidirectional.Text\x1a\x12.bidirectional.Res\"\x00\x12=\n\x0c\x43lientStream\x12\x14.bidirectional.Empty\x1a\x13.bidirectional.Text\"\x00\x30\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'wire_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _TEXT._serialized_start=29
  _TEXT._serialized_end=107
  _RES._serialized_start=109
  _RES._serialized_end=130
  _EMPTY._serialized_start=132
  _EMPTY._serialized_end=139
  _BIDIRECTIONAL._serialized_start=142
  _BIDIRECTIONAL._serialized_end=280
# @@protoc_insertion_point(module_scope)
